[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dropchad = "EQatKw7fYigPCJXTc5pYsQQCDJn5XNdqg7AtZJX8n5Ft"

[programs.devnet]
dropchad = "EQatKw7fYigPCJXTc5pYsQQCDJn5XNdqg7AtZJX8n5Ft"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# Rust tests on LiteSVM. No validator.
test = "cargo test"

[test]
skip_local_validator = true

[hooks]
